<a href="https://colab.research.google.com/github/hamednasr/DDoS-Attacks/blob/main/NN_Normalized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import GridSearchCV
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data = pd.read_csv('KDDTrain.csv')
data

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
1              0          0          0     0               0       0    0   
2              0        232       8153     0               0       0    0   
3              0        199        420     0               0       0    0   
4              0          0          0     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
125967         0          0          0     0               0       0    0   
125968         8        105        145     0               0       0    0   
125969         0       2231        384     0               0       0    0   
125970         0          0          0     0               0       0    0   
125971         0        151          0     0               0       0    0   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
1                       0          0                0  ...   
2                       0          1                0  ...   
3                       0          1                0  ...   
4                       0          0                0  ...   
...                   ...        ...              ...  ...   
125967                  0          0                0  ...   
125968                  0          0                0  ...   
125969                  0          1                0  ...   
125970                  0          0                0  ...   
125971                  0          1                0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
1                       26                    0.10                    0.05   
2                      255                    1.00                    0.00   
3                      255                    1.00                    0.00   
4                       19                    0.07                    0.07   
...                    ...                     ...                     ...   
125967                  25                    0.10                    0.06   
125968                 244                    0.96                    0.01   
125969                  30                    0.12                    0.06   
125970                   8                    0.03                    0.05   
125971                  77                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
1                              0.00                         0.00   
2                              0.03                         0.04   
3                              0.00                         0.00   
4                              0.00                         0.00   
...                             ...                          ...   
125967                         0.00                         0.00   
125968                         0.01                         0.00   
125969                         0.00                         0.00   
125970                         0.00                         0.00   
125971                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.00   
1                       1.00                      1.00                  0.00   
2                       0.03                      0.01                  0.00   
3                       0.00                      0.00                  0.00   
4                       0.00                      0.00                  1.00   
...                      ...                       ...                   ...   
125967                  

In [ ]:
# Remove rows contain null values (in the case there are null values)
# In our data, please remove the second row on csv file before importing the file

rows, columns = np.where(pd.isnull(data))
data_filtered = data.drop(labels=rows)

print("There are %d rows having null values" %(len(data) - len(data_filtered)))

data_filtered

There are 0 rows having null values


duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
1              0          0          0     0               0       0    0   
2              0        232       8153     0               0       0    0   
3              0        199        420     0               0       0    0   
4              0          0          0     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
125967         0          0          0     0               0       0    0   
125968         8        105        145     0               0       0    0   
125969         0       2231        384     0               0       0    0   
125970         0          0          0     0               0       0    0   
125971         0        151          0     0               0       0    0   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
1                       0          0                0  ...   
2                       0          1                0  ...   
3                       0          1                0  ...   
4                       0          0                0  ...   
...                   ...        ...              ...  ...   
125967                  0          0                0  ...   
125968                  0          0                0  ...   
125969                  0          1                0  ...   
125970                  0          0                0  ...   
125971                  0          1                0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
1                       26                    0.10                    0.05   
2                      255                    1.00                    0.00   
3                      255                    1.00                    0.00   
4                       19                    0.07                    0.07   
...                    ...                     ...                     ...   
125967                  25                    0.10                    0.06   
125968                 244                    0.96                    0.01   
125969                  30                    0.12                    0.06   
125970                   8                    0.03                    0.05   
125971                  77                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
1                              0.00                         0.00   
2                              0.03                         0.04   
3                              0.00                         0.00   
4                              0.00                         0.00   
...                             ...                          ...   
125967                         0.00                         0.00   
125968                         0.01                         0.00   
125969                         0.00                         0.00   
125970                         0.00                         0.00   
125971                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.00   
1                       1.00                      1.00                  0.00   
2                       0.03                      0.01                  0.00   
3                       0.00                      0.00                  0.00   
4                       0.00                      0.00                  1.00   
...                      ...                       ...                   ...   
125967                  

In [ ]:
# Remove duplicate rows

data_unduplicated = data_filtered.drop_duplicates()
print("There are %d duplicated rows" %(len(data_filtered) - len(data_unduplicated)))
data_unduplicated

There are 6356 duplicated rows


duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
1              0          0          0     0               0       0    0   
2              0        232       8153     0               0       0    0   
3              0        199        420     0               0       0    0   
4              0          0          0     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
125967         0          0          0     0               0       0    0   
125968         8        105        145     0               0       0    0   
125969         0       2231        384     0               0       0    0   
125970         0          0          0     0               0       0    0   
125971         0        151          0     0               0       0    0   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
1                       0          0                0  ...   
2                       0          1                0  ...   
3                       0          1                0  ...   
4                       0          0                0  ...   
...                   ...        ...              ...  ...   
125967                  0          0                0  ...   
125968                  0          0                0  ...   
125969                  0          1                0  ...   
125970                  0          0                0  ...   
125971                  0          1                0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
1                       26                    0.10                    0.05   
2                      255                    1.00                    0.00   
3                      255                    1.00                    0.00   
4                       19                    0.07                    0.07   
...                    ...                     ...                     ...   
125967                  25                    0.10                    0.06   
125968                 244                    0.96                    0.01   
125969                  30                    0.12                    0.06   
125970                   8                    0.03                    0.05   
125971                  77                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
1                              0.00                         0.00   
2                              0.03                         0.04   
3                              0.00                         0.00   
4                              0.00                         0.00   
...                             ...                          ...   
125967                         0.00                         0.00   
125968                         0.01                         0.00   
125969                         0.00                         0.00   
125970                         0.00                         0.00   
125971                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.00   
1                       1.00                      1.00                  0.00   
2                       0.03                      0.01                  0.00   
3                       0.00                      0.00                  0.00   
4                       0.00                      0.00                  1.00   
...                      ...                       ...                   ...   
125967                  

In [ ]:
# Define feature vectors and labels

X, y = data_unduplicated.iloc[:, :-1], data_unduplicated.iloc[:, -1]
print("Shape of X: %s" %str(X.shape), "- Type of X: %s" %str(type(X)))
print("Shape of y: %s" %str(y.shape), "- Type of y: %s" %str(type(y)))
y

Shape of X: (119616, 38) - Type of X: <class 'pandas.core.frame.DataFrame'>
Shape of y: (119616,) - Type of y: <class 'pandas.core.series.Series'>


0          normal
1         neptune
2          normal
3          normal
4         neptune
           ...   
125967    neptune
125968     normal
125969     normal
125970    neptune
125971     normal
Name: Label, Length: 119616, dtype: object

In [ ]:
# Classes of data

print("The number of original classes: %d" %len(y.unique()))
np.array(y).shape

The number of original classes: 23


(119616,)

In [ ]:
# Transform from 23 classes to 5 main classes of Internet attacks
# normal --> normal
# back, neptune, pod, smurf, teardrop --> DOS
# ipsweep, nmap, portsweep, satan --> Probing
# ftp_write, guess_passwd, imap, multihop, phf, spy, warezclient, warezmaster --> R2L
# buffer_overflow, loadmodule, perl, rootkit --> U2R

y_array = np.array(y)
y_encoded = np.zeros((y.shape))
for i in range(len(y_array)):
    if y_array[i] in ['normal']:
        y_array[i] = 'normal'
        y_encoded[i] = 0
    elif y_array[i] in ['back', 'land', 'neptune', 'pod', 'smurf', 'teardrop']:
        y_array[i] = 'DOS'
        y_encoded[i] = 1
    elif y_array[i] in ['ipsweep', 'nmap', 'portsweep', 'satan']:
        y_array[i] = 'probing'
        y_encoded[i] = 2
    elif y_array[i] in ['ftp_write', 'guess_passwd', 'imap', 'multihop', 'phf', 'spy', 'warezclient', 'warezmaster']:
        y_array[i] = 'R2L'
        y_encoded[i] = 3
    elif y_array[i] in ['buffer_overflow', 'loadmodule', 'perl', 'rootkit']:
        y_array[i] = 'U2R'
        y_encoded[i] = 4
y_df = pd.Series(y_array)
y_df.unique()

array(['normal', 'DOS', 'R2L', 'probing', 'U2R'], dtype=object)

In [ ]:
# Check the number of each class

#for name in y_df.unique():
for name in y_df.unique():
    print("The number of samples of class %s: %d" %(str(name), len(X[y_array==name])))
y_encoded[:10]

The number of samples of class normal: 67292
The number of samples of class DOS: 39893
The number of samples of class R2L: 995
The number of samples of class probing: 11384
The number of samples of class U2R: 52


array([0., 1., 0., 0., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Sort samples according to labels (optional)

data_new = X
data_new['Label'] = y_encoded
data_sorted = data_new.sort_values(by='Label')
data_sorted

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
71814          0        241       4198     0               0       0    0   
71813          0          0          0     0               0       0    0   
71812          0         45        127     0               0       0    0   
71810          0        206      12090     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
84225          0          0       5928     0               0       0    0   
99759        158       1567       3095     0               0       0    3   
108499        85        277        693     0               0       0    0   
82251          7        226        698     0               0       0    4   
89256         33       2402       3815     0               0       0    3   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
71814                   0          1                0  ...   
71813                   0          0                0  ...   
71812                   0          0                0  ...   
71810                   0          1                0  ...   
...                   ...        ...              ...  ...   
84225                   0          1                0  ...   
99759                   0          1                4  ...   
108499                  0          0                0  ...   
82251                   0          1                0  ...   
89256                   0          1                2  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
71814                  255                    1.00                    0.00   
71813                   93                    1.00                    0.00   
71812                  200                    0.85                    0.02   
71810                  255                    1.00                    0.00   
...                    ...                     ...                     ...   
84225                   82                    1.00                    0.00   
99759                    2                    1.00                    0.00   
108499                   1                    1.00                    0.00   
82251                    1                    1.00                    0.00   
89256                    3                    1.00                    0.00   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
71814                          0.50                         0.04   
71813                          0.08                         0.34   
71812                          0.85                         0.01   
71810                          0.17                         0.04   
...                             ...                          ...   
84225                          1.00                         0.02   
99759                          0.50                         0.00   
108499                         1.00                         0.00   
82251                          1.00                         0.00   
89256                          0.33                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                        0.0                       0.0                  0.00   
71814                    0.0                       0.0                  0.00   
71813                    0.0                       0.0                  1.00   
71812                    0.0                       0.0                  0.11   
71810                    0.0                       0.0                  0.00   
...                      ...                       ...                   ...   
84225                   

In [ ]:
# Split the training set and testing set
data_array = data_sorted.to_numpy()
X_new, y_new = data_array[:, :-1], data_array[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size=0.2, random_state=0)

In [ ]:
# Feature selection
feature_selection = SelectKBest(chi2, k=10).fit(X_train, y_train)
X_train_new = feature_selection.transform(X_train)
X_test_new = feature_selection.transform(X_test)
feature_selection.get_support()

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False,  True,  True, False, False, False, False, False,  True,
       False, False])

In [ ]:
################################## CASE 2 ################################
##################### ---- WITH NORMALIZATION STEP -----##############
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
X_train_scaled = std_scaler.fit_transform(X_train_new)
X_test_scaled = std_scaler.fit_transform(X_test_new)
X_train_scaled.shape

(95692, 10)

In [ ]:
## Neural Network - one hidden layer - With Normalization
hidden_layer_sizes_=[(12,),(25,),(50,),(100,),(200,),(300,),(400,)]
activation_=['identity', 'logistic', 'tanh', 'relu']

param_grid = [{'hidden_layer_sizes': hidden_layer_sizes_, 'activation': activation_}]

grid_search = GridSearchCV(MLPClassifier(), 
                           param_grid=param_grid, 
                           cv=5,
                           scoring='f1_weighted',
                           n_jobs=-1,
                          verbose=2)

grid_search.fit(X_train_scaled, y_train)
mlpc1_clf = grid_search.best_estimator_
mlpc1_clf

Fitting 5 folds for each of 28 candidates, totalling 140 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   24.9s
[Parallel(n_jobs=-1)]: Done 140 out of 140 | elapsed: 25.3min finished
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(300,))

In [ ]:
mlpc1=MLPClassifier(hidden_layer_sizes=(300,),activation='logistic',max_iter=1000)
mlpc1.fit(X_train_scaled,y_train)

MLPClassifier(activation='logistic', hidden_layer_sizes=(300,), max_iter=1000)

In [ ]:
y_train_pred = mlpc1.predict(X_train_scaled)
y_test_pred = mlpc1.predict(X_test_scaled)

In [ ]:
# check Accuaracy on Traing and Testing Data
train_accuracy_mlpc1 = mlpc1.score(X_train_scaled,y_train)
print("Train Accuaracy: " , train_accuracy_mlpc1)

test_accuracy_mlpc1 = mlpc1.score(X_test_scaled,y_test)
print("Test Accuaracy: " , test_accuracy_mlpc1)


Train Accuaracy:  0.9508004848890189
Test Accuaracy:  0.9116786490553419


In [ ]:
print(confusion_matrix(y_test, y_test_pred))
print("==================================")
print(classification_report(y_test, y_test_pred))

[[11893   188  1342    18     0]
 [  165  7656   172     7     0]
 [   62    13  2186     0     0]
 [   47     6    88    73     0]
 [    4     0     1     0     3]]
              precision    recall  f1-score   support

         0.0       0.98      0.88      0.93     13441
         1.0       0.97      0.96      0.97      8000
         2.0       0.58      0.97      0.72      2261
         3.0       0.74      0.34      0.47       214
         4.0       1.00      0.38      0.55         8

    accuracy                           0.91     23924
   macro avg       0.85      0.70      0.73     23924
weighted avg       0.94      0.91      0.92     23924



In [ ]:
## Neural Network - two hidden layers - With Normalization
hidden_layer_sizes_=[(50,200),(100,300),(100,500),(200,400),(200,600),(300,600),(300,800)]
activation_=['logistic', 'tanh', 'relu']

param_grid = [{'hidden_layer_sizes': hidden_layer_sizes_, 'activation': activation_}]

grid_search = GridSearchCV(MLPClassifier(), 
                           param_grid=param_grid, 
                           cv=5,
                           scoring='f1_weighted',
                           n_jobs=-1,
                          verbose=3)

grid_search.fit(X_train_scaled, y_train)
mlpc2_clf = grid_search.best_estimator_
mlpc2_clf

Fitting 5 folds for each of 21 candidates, totalling 105 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed: 10.4min
[Parallel(n_jobs=-1)]: Done 105 out of 105 | elapsed: 414.4min finished


MLPClassifier(hidden_layer_sizes=(200, 600))

In [ ]:
mlpc2=MLPClassifier(hidden_layer_sizes=(200,600),max_iter=1000)
mlpc2.fit(X_train_scaled,y_train)

MLPClassifier(hidden_layer_sizes=(200, 600), max_iter=1000)

In [ ]:
y_train_pred2 = mlpc2.predict(X_train_scaled)
y_test_pred2 = mlpc2.predict(X_test_scaled)

In [ ]:
# check Accuaracy on Traing and Testing Data
train_accuracy_mlpc2 = mlpc2.score(X_train_scaled,y_train)
print("Train Accuaracy: " , train_accuracy_mlpc2)

test_accuracy_mlpc2 = mlpc2.score(X_test_scaled,y_test)
print("Test Accuaracy: " , test_accuracy_mlpc2)

Train Accuaracy:  0.9579693182293191
Test Accuaracy:  0.850986457114195


In [ ]:
print(confusion_matrix(y_test, y_test_pred2))
print("==================================")
print(classification_report(y_test, y_test_pred2))

[[10414    86  2908    32     1]
 [  209  7661   128     1     1]
 [   43    28  2190     0     0]
 [    7     1   113    91     2]
 [    4     0     1     0     3]]
              precision    recall  f1-score   support

         0.0       0.98      0.77      0.86     13441
         1.0       0.99      0.96      0.97      8000
         2.0       0.41      0.97      0.58      2261
         3.0       0.73      0.43      0.54       214
         4.0       0.43      0.38      0.40         8

    accuracy                           0.85     23924
   macro avg       0.71      0.70      0.67     23924
weighted avg       0.92      0.85      0.87     23924

