<a href="https://colab.research.google.com/github/hamednasr/DDoS-Attacks/blob/main/SVM_Normalized.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import common libraries

import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
#from google.colab import files
#uploaded = files.upload()

In [ ]:
data = pd.read_csv('KDDTrain.csv')
data

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
1              0          0          0     0               0       0    0   
2              0        232       8153     0               0       0    0   
3              0        199        420     0               0       0    0   
4              0          0          0     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
125967         0          0          0     0               0       0    0   
125968         8        105        145     0               0       0    0   
125969         0       2231        384     0               0       0    0   
125970         0          0          0     0               0       0    0   
125971         0        151          0     0               0       0    0   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
1                       0          0                0  ...   
2                       0          1                0  ...   
3                       0          1                0  ...   
4                       0          0                0  ...   
...                   ...        ...              ...  ...   
125967                  0          0                0  ...   
125968                  0          0                0  ...   
125969                  0          1                0  ...   
125970                  0          0                0  ...   
125971                  0          1                0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
1                       26                    0.10                    0.05   
2                      255                    1.00                    0.00   
3                      255                    1.00                    0.00   
4                       19                    0.07                    0.07   
...                    ...                     ...                     ...   
125967                  25                    0.10                    0.06   
125968                 244                    0.96                    0.01   
125969                  30                    0.12                    0.06   
125970                   8                    0.03                    0.05   
125971                  77                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
1                              0.00                         0.00   
2                              0.03                         0.04   
3                              0.00                         0.00   
4                              0.00                         0.00   
...                             ...                          ...   
125967                         0.00                         0.00   
125968                         0.01                         0.00   
125969                         0.00                         0.00   
125970                         0.00                         0.00   
125971                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.00   
1                       1.00                      1.00                  0.00   
2                       0.03                      0.01                  0.00   
3                       0.00                      0.00                  0.00   
4                       0.00                      0.00                  1.00   
...                      ...                       ...                   ...   
125967                  

In [ ]:
# Remove rows contain null values (in the case there are null values)
# In our data, please remove the second row on csv file before importing the file

rows, columns = np.where(pd.isnull(data))
data_filtered = data.drop(labels=rows)

print("There are %d rows having null values" %(len(data) - len(data_filtered)))

data_filtered

There are 0 rows having null values


duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
1              0          0          0     0               0       0    0   
2              0        232       8153     0               0       0    0   
3              0        199        420     0               0       0    0   
4              0          0          0     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
125967         0          0          0     0               0       0    0   
125968         8        105        145     0               0       0    0   
125969         0       2231        384     0               0       0    0   
125970         0          0          0     0               0       0    0   
125971         0        151          0     0               0       0    0   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
1                       0          0                0  ...   
2                       0          1                0  ...   
3                       0          1                0  ...   
4                       0          0                0  ...   
...                   ...        ...              ...  ...   
125967                  0          0                0  ...   
125968                  0          0                0  ...   
125969                  0          1                0  ...   
125970                  0          0                0  ...   
125971                  0          1                0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
1                       26                    0.10                    0.05   
2                      255                    1.00                    0.00   
3                      255                    1.00                    0.00   
4                       19                    0.07                    0.07   
...                    ...                     ...                     ...   
125967                  25                    0.10                    0.06   
125968                 244                    0.96                    0.01   
125969                  30                    0.12                    0.06   
125970                   8                    0.03                    0.05   
125971                  77                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
1                              0.00                         0.00   
2                              0.03                         0.04   
3                              0.00                         0.00   
4                              0.00                         0.00   
...                             ...                          ...   
125967                         0.00                         0.00   
125968                         0.01                         0.00   
125969                         0.00                         0.00   
125970                         0.00                         0.00   
125971                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.00   
1                       1.00                      1.00                  0.00   
2                       0.03                      0.01                  0.00   
3                       0.00                      0.00                  0.00   
4                       0.00                      0.00                  1.00   
...                      ...                       ...                   ...   
125967                  

In [ ]:
# Remove duplicate rows

data_unduplicated = data_filtered.drop_duplicates()
print("There are %d duplicated rows" %(len(data_filtered) - len(data_unduplicated)))
data_unduplicated

There are 6356 duplicated rows


duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
1              0          0          0     0               0       0    0   
2              0        232       8153     0               0       0    0   
3              0        199        420     0               0       0    0   
4              0          0          0     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
125967         0          0          0     0               0       0    0   
125968         8        105        145     0               0       0    0   
125969         0       2231        384     0               0       0    0   
125970         0          0          0     0               0       0    0   
125971         0        151          0     0               0       0    0   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
1                       0          0                0  ...   
2                       0          1                0  ...   
3                       0          1                0  ...   
4                       0          0                0  ...   
...                   ...        ...              ...  ...   
125967                  0          0                0  ...   
125968                  0          0                0  ...   
125969                  0          1                0  ...   
125970                  0          0                0  ...   
125971                  0          1                0  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
1                       26                    0.10                    0.05   
2                      255                    1.00                    0.00   
3                      255                    1.00                    0.00   
4                       19                    0.07                    0.07   
...                    ...                     ...                     ...   
125967                  25                    0.10                    0.06   
125968                 244                    0.96                    0.01   
125969                  30                    0.12                    0.06   
125970                   8                    0.03                    0.05   
125971                  77                    0.30                    0.03   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
1                              0.00                         0.00   
2                              0.03                         0.04   
3                              0.00                         0.00   
4                              0.00                         0.00   
...                             ...                          ...   
125967                         0.00                         0.00   
125968                         0.01                         0.00   
125969                         0.00                         0.00   
125970                         0.00                         0.00   
125971                         0.30                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                       0.00                      0.00                  0.00   
1                       1.00                      1.00                  0.00   
2                       0.03                      0.01                  0.00   
3                       0.00                      0.00                  0.00   
4                       0.00                      0.00                  1.00   
...                      ...                       ...                   ...   
125967                  

In [ ]:
# Define feature vectors and labels

X, y = data_unduplicated.iloc[:, :-1], data_unduplicated.iloc[:, -1]
print("Shape of X: %s" %str(X.shape), "- Type of X: %s" %str(type(X)))
print("Shape of y: %s" %str(y.shape), "- Type of y: %s" %str(type(y)))
y

Shape of X: (119616, 38) - Type of X: <class 'pandas.core.frame.DataFrame'>
Shape of y: (119616,) - Type of y: <class 'pandas.core.series.Series'>


0          normal
1         neptune
2          normal
3          normal
4         neptune
           ...   
125967    neptune
125968     normal
125969     normal
125970    neptune
125971     normal
Name: Label, Length: 119616, dtype: object

In [ ]:
# Classes of data

print("The number of original classes: %d" %len(y.unique()))
np.array(y).shape

The number of original classes: 23


(119616,)

In [ ]:
# Transform from 23 classes to 5 main classes of Internet attacks
# normal --> normal
# back, neptune, pod, smurf, teardrop --> DOS
# ipsweep, nmap, portsweep, satan --> Probing
# ftp_write, guess_passwd, imap, multihop, phf, spy, warezclient, warezmaster --> R2L
# buffer_overflow, loadmodule, perl, rootkit --> U2R

y_array = np.array(y)
y_encoded = np.zeros((y.shape))
for i in range(len(y_array)):
    if y_array[i] in ['normal']:
        y_array[i] = 'normal'
        y_encoded[i] = 0
    elif y_array[i] in ['back', 'land', 'neptune', 'pod', 'smurf', 'teardrop']:
        y_array[i] = 'DOS'
        y_encoded[i] = 1
    elif y_array[i] in ['ipsweep', 'nmap', 'portsweep', 'satan']:
        y_array[i] = 'probing'
        y_encoded[i] = 2
    elif y_array[i] in ['ftp_write', 'guess_passwd', 'imap', 'multihop', 'phf', 'spy', 'warezclient', 'warezmaster']:
        y_array[i] = 'R2L'
        y_encoded[i] = 3
    elif y_array[i] in ['buffer_overflow', 'loadmodule', 'perl', 'rootkit']:
        y_array[i] = 'U2R'
        y_encoded[i] = 4
y_df = pd.Series(y_array)
y_df.unique()

array(['normal', 'DOS', 'R2L', 'probing', 'U2R'], dtype=object)

In [ ]:
# Check the number of each class

#for name in y_df.unique():
for name in y_df.unique():
    print("The number of samples of class %s: %d" %(str(name), len(X[y_array==name])))
y_encoded[:10]

The number of samples of class normal: 67292
The number of samples of class DOS: 39893
The number of samples of class R2L: 995
The number of samples of class probing: 11384
The number of samples of class U2R: 52


array([0., 1., 0., 0., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Sort samples according to labels (optional)

data_new = X
data_new['Label'] = y_encoded
data_sorted = data_new.sort_values(by='Label')

data_sorted

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0              0        146          0     0               0       0    0   
71814          0        241       4198     0               0       0    0   
71813          0          0          0     0               0       0    0   
71812          0         45        127     0               0       0    0   
71810          0        206      12090     0               0       0    0   
...          ...        ...        ...   ...             ...     ...  ...   
84225          0          0       5928     0               0       0    0   
99759        158       1567       3095     0               0       0    3   
108499        85        277        693     0               0       0    0   
82251          7        226        698     0               0       0    4   
89256         33       2402       3815     0               0       0    3   

        num_failed_logins  logged_in  num_compromised  ...  \
0                       0          0                0  ...   
71814                   0          1                0  ...   
71813                   0          0                0  ...   
71812                   0          0                0  ...   
71810                   0          1                0  ...   
...                   ...        ...              ...  ...   
84225                   0          1                0  ...   
99759                   0          1                4  ...   
108499                  0          0                0  ...   
82251                   0          1                0  ...   
89256                   0          1                2  ...   

        dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                        1                    0.00                    0.60   
71814                  255                    1.00                    0.00   
71813                   93                    1.00                    0.00   
71812                  200                    0.85                    0.02   
71810                  255                    1.00                    0.00   
...                    ...                     ...                     ...   
84225                   82                    1.00                    0.00   
99759                    2                    1.00                    0.00   
108499                   1                    1.00                    0.00   
82251                    1                    1.00                    0.00   
89256                    3                    1.00                    0.00   

        dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                              0.88                         0.00   
71814                          0.50                         0.04   
71813                          0.08                         0.34   
71812                          0.85                         0.01   
71810                          0.17                         0.04   
...                             ...                          ...   
84225                          1.00                         0.02   
99759                          0.50                         0.00   
108499                         1.00                         0.00   
82251                          1.00                         0.00   
89256                          0.33                         0.00   

        dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                        0.0                       0.0                  0.00   
71814                    0.0                       0.0                  0.00   
71813                    0.0                       0.0                  1.00   
71812                    0.0                       0.0                  0.11   
71810                    0.0                       0.0                  0.00   
...                      ...                       ...                   ...   
84225                   

In [ ]:
# Split the training set and testing set
data_array = data_sorted.to_numpy()
X_new, y_new = data_array[:, :-1], data_array[:, -1]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y_new, test_size=0.2, random_state=0)

# Feature selection
feature_selection = SelectKBest(chi2, k=10).fit(X_train, y_train)
X_train_new = feature_selection.transform(X_train)
X_test_new = feature_selection.transform(X_test)
feature_selection.get_support()

array([ True,  True,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True, False,  True, False, False, False, False,
       False,  True,  True, False, False, False, False, False,  True,
       False, False])

In [ ]:
################################## CASE 2 ################################
##################### ---- WITH NORMALIZATION STEP -----##############
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
X_train_scaled = std_scaler.fit_transform(X_train_new)
X_test_scaled = std_scaler.fit_transform(X_test_new)
X_train_scaled.shape

(95692, 10)

In [ ]:
## SVM - With Normalization

C = [2**i for i in range(0, 8)]
gamma = [2**j for j in range(-8,9)]
param_grid = [{'C': C, 'gamma': gamma}]
grid_search = GridSearchCV(SVC(), param_grid=param_grid, cv=5,
                           scoring='f1_weighted',
                           return_train_score=True)
# Get small proportion of data to find best estimator
X_train_sub, _, y_train_sub, _ = train_test_split(X_train_scaled, y_train, test_size=0.8, random_state=0)
grid_search.fit(X_train_sub, y_train_sub)
svm_clf = grid_search.best_estimator_
svm_clf

SVC(C=128, gamma=4)

In [ ]:
################################## CASE 2 ################################
##################### ---- Apply SVM with Normalization -----##############
svm_clf_rand = SVC(kernel='rbf', C=128, gamma=4, random_state=0)
svm_clf_rand.fit(X_train_scaled, y_train)

y_trn_pred = svm_clf_rand.predict(X_train_scaled)
y_tst_pred = svm_clf_rand.predict(X_test_scaled)



In [ ]:
# check Accuaracy on Traing and Testing Data
train_accuracy_rand = svm_clf_rand.score(X_train_scaled,y_train)
print("Train Accuaracy: " , train_accuracy_rand)

test_accuracy_rand = svm_clf_rand.score(X_test_scaled, y_test)
print("Test Accuaracy: " , test_accuracy_rand)

Train Accuaracy:  0.9638632278560382
Test Accuaracy:  0.9250961377696038


In [ ]:
print(confusion_matrix(y_test,y_tst_pred))
print("====================")
print(classification_report(y_test, y_tst_pred))

[[12212    64  1128    36     1]
 [  197  7695   105     0     3]
 [   81    20  2158     2     0]
 [  116     0    32    64     2]
 [    3     0     2     0     3]]
              precision    recall  f1-score   support

         0.0       0.97      0.91      0.94     13441
         1.0       0.99      0.96      0.98      8000
         2.0       0.63      0.95      0.76      2261
         3.0       0.63      0.30      0.41       214
         4.0       0.33      0.38      0.35         8

    accuracy                           0.93     23924
   macro avg       0.71      0.70      0.69     23924
weighted avg       0.94      0.93      0.93     23924

